name: Publish

on:
  push:

jobs:

  publish-github:
    name: Publish to release branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run release
      run: "sh/genRelease.sh"
      shell: bash
